### PR TITLE
Prefer genexpr to listcomp

### PR DESCRIPTION
**Pull request by bswck**
Saves one iteration.
I made this PR from my mobile phone 💀

### CODE REVIEW

**Comment by pawamoy** [comment]
Oh, didn't think you could unpack a genexpr! This code is templated, would you mind sending that PR to my copier-uv instead :p ?

**Comment by pawamoy** [comment]
Merging anyway, I'll apply this change to the template :slightly_smiling_face:

**Comment by bswck** [comment]
@pawamoy I'd like to open a PR to revert this. It wastes time on creating a frame from genexpr, completely ignoring the wins of PEP 709 inlined comprehensions on small-sized data.

**Comment by pawamoy** [comment]
Don't bother, this code is meant to go away. I plan on automating this in a third-party package, so I can remove this boilerplate from all my projects.

**Pull request merged**
